location:
  world_name: "world"
  lobby:
    x:
    y:
    z:
  core:
    red:
      x:
      y:
      z:
    blue:
      x:
      y:
      z:
  spawn:
    red:
      x:
      y:
      z:
    blue:
      x:
      y:
      z: